package com.civicconnect.identity.enums;

public enum AuditAction {
    // User / Auth
    USER_REGISTERED,
    USER_LOGIN,
    USER_STATUS_UPDATED,
    USER_ROLE_UPDATED,
    USER_DEACTIVATED,

    // Citizen
    CITIZEN_PROFILE_CREATED,
    CITIZEN_PROFILE_UPDATED,

    // Documents
    DOCUMENT_UPLOADED,
    DOCUMENT_VERIFIED,
    DOCUMENT_REJECTED,

    // Service Requests
    SERVICE_REQUEST_CREATED,
    SERVICE_REQUEST_ASSIGNED,
    SERVICE_REQUEST_STATUS_UPDATED,
    SERVICE_REQUEST_WITHDRAWN,
    SERVICE_REQUEST_CLOSED,

    // Resolution / Workflow
    RESOLUTION_CREATED,
    RESOLUTION_COMPLETED,
    WORKFLOW_STEP_CREATED,
    WORKFLOW_STEP_STATUS_UPDATED,

    // Staff
    STAFF_CREATED,
    STAFF_STATUS_UPDATED,
    STAFF_PROFILE_UPDATED,

    // Feedback
    FEEDBACK_SUBMITTED,
    SATISFACTION_METRIC_UPDATED,

    // Compliance
    COMPLIANCE_RECORD_CREATED,
    AUDIT_CREATED,
    AUDIT_STATUS_UPDATED,
    AUDIT_FINDINGS_UPDATED,

    // Reporting
    REPORT_GENERATED,

    // Notifications
    NOTIFICATION_SENT,
    NOTIFICATION_READ,
    NOTIFICATION_DISMISSED
}
