import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { getAllReports, generateReport, getReportsByScope } from '../../services/api';
import { useAuth } from '../../context/AuthContext';
import { toast } from 'react-toastify';
import { PageHeader } from '../../components/ui';

const scopeIcon = (s) => s === 'REQUEST' ? '📋' : s === 'FEEDBACK' ? '⭐' : s === 'COMPLIANCE' ? '🛡️' : '🏢';
const scopeBadge = (s) => (
  <span className={`badge ${s === 'REQUEST' ? 'badge-submitted' : s === 'FEEDBACK' ? 'badge-assigned' : s === 'COMPLIANCE' ? 'badge-in_progress' : 'badge-resolved'}`}>
    {scopeIcon(s)} {s}
  </span>
);

const scopes = ['REQUEST', 'FEEDBACK', 'COMPLIANCE', 'DEPARTMENT'];

export default function ReportsDashboardPage() {
  const { user } = useAuth();
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(null);
  const [filterScope, setFilterScope] = useState('ALL');
  const [selectedReport, setSelectedReport] = useState(null);

  const canGenerate = ['DEPARTMENT_HEAD', 'CITY_ADMINISTRATOR'].includes(user.role);

  const fetchReports = async () => {
    try {
      const res = filterScope === 'ALL'
        ? await getAllReports()
        : await getReportsByScope(filterScope);
      setReports(res.data);
    } catch {
      toast.error('Failed to load reports.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { setLoading(true); fetchReports(); }, [filterScope]);

  const handleGenerate = async (scope) => {
    setGenerating(scope);
    try {
      const res = await generateReport(scope);
      toast.success(`✅ ${scope} report generated!`);
      setReports(prev => [res.data, ...prev]);
    } catch (err) {
      toast.error(err.response?.data?.message || `Failed to generate ${scope} report.`);
    } finally {
      setGenerating(null);
    }
  };

  const parseMetrics = (metricsStr) => {
    try { return JSON.parse(metricsStr); } catch { return null; }
  };

  if (loading) return <div className="loading"><div className="spinner"></div><br />Loading...</div>;

  return (
    <>
      <PageHeader icon="📊" title="Reports Dashboard" subtitle="Generate and view aggregated reports across all CivicConnect services." />

      {/* Generate buttons */}
      {canGenerate && (
        <div className="card">
          <div className="card-title"><span className="icon icon-blue">⚡</span> Generate New Report</div>
          <p style={{ color: 'var(--gray-500)', marginBottom: 20, fontSize: '.9rem' }}>
            Generate a live report by pulling real-time data from all services.
          </p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 12 }}>
            {scopes.map(scope => (
              <button key={scope} className="btn btn-outline" style={{ padding: '20px 16px', flexDirection: 'column', gap: 8 }}
                onClick={() => handleGenerate(scope)} disabled={generating !== null}>
                <span style={{ fontSize: '1.8rem' }}>{scopeIcon(scope)}</span>
                <span style={{ fontWeight: 800 }}>{scope}</span>
                <span style={{ fontSize: '.75rem', color: 'var(--gray-400)', fontWeight: 500 }}>
                  {scope === 'REQUEST' ? 'Service request stats' : scope === 'FEEDBACK' ? 'Satisfaction metrics' : scope === 'COMPLIANCE' ? 'Compliance & audit' : 'Department overview'}
                </span>
                {generating === scope && <span>⏳ Generating...</span>}
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Filter */}
      <div className="card">
        <div className="card-title"><span className="icon icon-green">📁</span> Reports ({reports.length})</div>
        <div style={{ display: 'flex', gap: 8, marginBottom: 20, flexWrap: 'wrap' }}>
          <button className={`btn btn-small ${filterScope === 'ALL' ? 'btn-primary' : 'btn-outline'}`} onClick={() => setFilterScope('ALL')}>All</button>
          {scopes.map(s => (
            <button key={s} className={`btn btn-small ${filterScope === s ? 'btn-primary' : 'btn-outline'}`} onClick={() => setFilterScope(s)}>
              {scopeIcon(s)} {s}
            </button>
          ))}
        </div>

        {reports.length === 0 ? (
          <div className="empty-state">
            <div className="empty-icon">📊</div>
            <h3>No reports yet</h3>
            <p>{canGenerate ? 'Generate your first report using the buttons above.' : 'Reports will appear here once generated.'}</p>
          </div>
        ) : (
          <div className="table-container">
            <table>
              <thead><tr><th>ID</th><th>Scope</th><th>Generated By</th><th>Date</th><th>Actions</th></tr></thead>
              <tbody>
                {reports.map(r => (
                  <tr key={r.reportId}>
                    <td style={{ fontWeight: 700 }}>#{r.reportId}</td>
                    <td>{scopeBadge(r.scope)}</td>
                    <td>{r.generatedByName}</td>
                    <td>{new Date(r.generatedDate).toLocaleString()}</td>
                    <td>
                      <button className="btn btn-small btn-secondary" onClick={() => setSelectedReport(r)}>👁️ View</button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Report Detail Modal */}
      {selectedReport && (
        <div className="modal-overlay" onClick={() => setSelectedReport(null)}>
          <div className="modal" onClick={e => e.stopPropagation()} style={{ maxWidth: 650, maxHeight: '80vh', overflow: 'auto' }}>
            <h3>{scopeIcon(selectedReport.scope)} Report #{selectedReport.reportId} — {selectedReport.scope}</h3>
            <div className="profile-grid" style={{ marginBottom: 20 }}>
              <div className="profile-item"><label>👤 Generated By</label><div className="value">{selectedReport.generatedByName}</div></div>
              <div className="profile-item"><label>📅 Date</label><div className="value">{new Date(selectedReport.generatedDate).toLocaleString()}</div></div>
            </div>

            {/* Metrics display */}
            <div style={{ background: 'var(--gray-50)', borderRadius: 14, padding: 20, border: '1px solid var(--gray-100)' }}>
              <label style={{ fontSize: '.75rem', fontWeight: 800, color: 'var(--gray-400)', textTransform: 'uppercase', letterSpacing: 1, display: 'block', marginBottom: 12 }}>
                📊 Report Metrics
              </label>
              {(() => {
                const parsed = parseMetrics(selectedReport.metrics);
                if (parsed && typeof parsed === 'object') {
                  return (
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
                      {Object.entries(parsed).map(([key, val]) => (
                        <div key={key} style={{ padding: 14, background: 'var(--white)', borderRadius: 10, border: '1px solid var(--gray-100)' }}>
                          <div style={{ fontSize: '.72rem', fontWeight: 800, color: 'var(--gray-400)', textTransform: 'uppercase', letterSpacing: .8, marginBottom: 4 }}>
                            {key.replace(/([A-Z])/g, ' $1').replace(/_/g, ' ')}
                          </div>
                          <div style={{ fontSize: '1.2rem', fontWeight: 800, color: 'var(--dark)' }}>
                            {typeof val === 'number' ? val.toLocaleString() : typeof val === 'object' ? JSON.stringify(val) : String(val)}
                          </div>
                        </div>
                      ))}
                    </div>
                  );
                }
                return <pre style={{ whiteSpace: 'pre-wrap', fontSize: '.9rem', color: 'var(--gray-700)', lineHeight: 1.6 }}>{selectedReport.metrics}</pre>;
              })()}
            </div>

            <div className="actions-row">
              <button className="btn btn-secondary" onClick={() => setSelectedReport(null)}>✕ Close</button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}

